### ISSUE TITLE
Pagination shows one page too much

### ISSUE THREAD

**Issue by Vencarii** [Scalesoft/s-pagination#1]
I had an issue with your pagination plugin, the page counter was always too high by one page.

I wrote a fix that works pretty well for me, maybe you want to implement it to your code:

```
// ----- original code -----
//this.pageCount = Math.ceil(itemsCount / itemsOnPage);

// ----- my fix -----
var myPageCount = itemsCount / itemsOnPage;

// integer
if (myPageCount % 1 === 0) {
    this.pageCount = myPageCount - 1;
}
// float
else {
    this.pageCount = Math.floor(itemsCount / itemsOnPage);
}
```

**Comment by vladapokorny** [comment]
I think that our code is already correct. If there is any item, then there must be at least one page. If there are more items than the page size, then there must be more than one page. For example: if page size is set to 10 a we have 11 items, then first page contains 10 items and second page contains 1 item.

Maybe this doesn’t suit to you, but in our case this is expected behavior.

**Comment by MudraMartin** [comment]
Do you have some code to reproduce the issue you are describing? We would take a second look and implement a quick fix. As @vladapokorny  stated - lets have an example with pagesize of **3** items per page. When itemsCount is **7**:

1. Items 1,2,3
2. Items 4,5,6
3. Item 7

Thats a pageCount **3**

---------------------------------

When the pagesize is **5**
1. Items 1,2,3,4,5
2. Items 6,7

Thats pageCount **2**

**Comment by Vencarii** [comment]
I had problems in situations like this:
pagesize: 15
items: 15

1. items 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
2. [empty page]

I use this code, hope it helps:


```
// I send an AJAX request once to get the total number of items I have, I want to show 15 items/page

$.get('/get/data/count', function (data) {

    myPagination = new Pagination({

        container: $('#pagination-' + id),

        maxVisibleElements: 13,

        enhancedMode: true,

        pageClickCallback: myCallback

    });


    myPagination.make(data, 15);

    $('#pagination-' + id).show();

});
```


```
// callback function to fetch items for the current page

function myCallback(page) {

    $('#myTable tbody').load('get/current/data/'+page, function() {

        // do some stuff not related to pagination...

    }

}
```

**Comment by vladapokorny** [comment]
I tried reproduce this issue using your code with little modification (without using AJAX call to the server), but without success. I used this code snippet:

```
        var data = 15;
        myPagination = new Pagination({
            container: $('#pagination-1'),
            maxVisibleElements: 13,
            enhancedMode: true,
            pageClickCallback: myCallback
        });

        myPagination.make(data, 15);
        $('#pagination-1').show();
```

After that, the component was rendered correctly as three buttons: [<<] [1] [>>]

**Comment by MudraMartin** [comment]
Yeah we do see that this example returns only a single page [1]. Did our framework really returned two pages?

**Comment by Vencarii** [comment]
I'm working on another implementation these days, I will let you guys know if there is an error again or if it was my mistake in the first place. :-)

**Comment by MudraMartin** [comment]
We are going to release a new version with some bugfixes. Closing this issue as obsolete for the moment.
