### ISSUE TITLE
Can this be used with webpack?

### ISSUE THREAD

**Issue by jonesnc** [Scalesoft/s-pagination#3]
Can this be used with webpack?

When I try to import it with `import Pagination from 's-pagination'`, I get this error:

`TypeError: s_pagination__WEBPACK_IMPORTED_MODULE_6___default.a is not a constructor`

**Comment by vladapokorny** [comment]
S-Pagination is currently a simple JavaScript library that doesn't use any modular system (e.g. AMD or CommonJS). It is a globally defined Pagination class.

I don't know what exactly involves using webpack, but if it requires converting the library to support modular systems, you can create pull request with this feature. The possibility to use the library as a global class without a modular system must be kept.

**Comment by MudraMartin** [comment]
From now it can be used with web pack without problems. We added support and we are currently using this with webpack.
