### ISSUE TITLE
Set page item count dynamically

### ISSUE THREAD

**Issue by tnlthanzeel** [Scalesoft/s-pagination#6]
we need to set page item count dynamically. how is that possible here?

**Comment by vladapokorny** [comment]
It is possible to call the method `make(itemsCount, itemsOnPage, defaultPageNumber)` repeatedly to change the item count dynamically.

**Comment by tnlthanzeel** [comment]
> It is possible to call the method `make(itemsCount, itemsOnPage, defaultPageNumber)` repeatedly to change the item count dynamically.

We tried this, it works, but it duplicates the pagination each tome we call the make function

**Comment by vladapokorny** [comment]
Which version do you use? I don't have any problem calling the method `make` repeatedly in the latest version 3.0.1. Could you provide more details?

**Comment by vladapokorny** [comment]
No response for over 4 months. Closing.
